// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "cpp/check.hpp"
#include "cpp/exch.hpp"
#include "cpp/list.hpp"
#include "cpp/math.hpp"
#include "cpp/rbtree.hpp"
#include "cpp/string.hpp"
