// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "pl2d/drawable.h"
#include "pl2d/matrix.h"
#include "pl2d/pixel.h"
#ifdef __cplusplus
}
#endif
