// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "plds/base/fb.hpp"
#include "plds/base/wnd.hpp"
#include "plds/server/api.hpp"
#include "plds/server/var.hpp"
